name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

    - name: Build the Docker image
      run: |
        IMAGE_NAME=${{ secrets.DOCKERHUB_USERNAME }}/py-test-jenkins-docker
        TAG=$(date +%s)
        docker build -t $IMAGE_NAME:$TAG .
        docker tag $IMAGE_NAME:$TAG $IMAGE_NAME:latest

    - name: Push image to Docker Hub
      run: |
        IMAGE_NAME=${{ secrets.DOCKERHUB_USERNAME }}/py-test-jenkins-docker
        TAG=$(date +%s)
        docker push $IMAGE_NAME:$TAG
        docker push $IMAGE_NAME:latest

